name: Deploy Azure Resources

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login with Azure
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"

      - name: Deploy the Bicep Script
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: "Adonis-RG"
          template: azure-resources.bicep
